swagger:
  kafka:
    - groupName: sdp
      bootstrapServer: kafka1.public-sdp-kafka.squadex.devopskzn.ru:9092
      schemaRegistryUrl: http://schema-registry.sdp-kafka.squadex.devopskzn.ru
      consumerConfig:
        "[security.protocol]": SSL
      producerConfig:
        "[security.protocol]": SSL
