version: '2'
services:
  kafka-swagger-rest:
    image: kafka-swagger-rest:0.1-SNAPSHOT-latest
    ports:
      - 8080:8080
    command: [ "java", "-Dreactor.netty.http.server.accessLogEnabled=true",
               "-jar", "/kafka-swagger-rest-0.1-SNAPSHOT.jar"]
    environment:
      swagger.kafka[0].groupName: 'sdp-kafka'
      swagger.kafka[0].bootstrapServers: 'kafka1.public-sdp-kafka.squadex.devopskzn.ru:9092'
      swagger.kafka[0].schemaRegistryUrl: 'http://schema-registry.sdp-kafka.squadex.devopskzn.ru'
      swagger.kafka[0].consumerConfig."[security.protocol]": 'SSL'
      swagger.kafka[0].producerConfig."[security.protocol]": 'SSL'
