version: '2'
services:
  kafka-swagger-rest:
    image: kafka-swagger-rest:0.1-SNAPSHOT-latest
    ports:
      - 8080:8080
    command: [ "java", "-Dreactor.netty.http.server.accessLogEnabled=true",
               "-jar", "/kafka-swagger-rest-0.1-SNAPSHOT.jar"]
    environment:
      swagger_kafka[0]_groupName: 'sdp-kafka'
      swagger_kafka[0]_bootstrapServer: 'kafka1.public-sdp-kafka.squadex.devopskzn.ru:9092'
      swagger_kafka[0]_schemaRegistryUrl: 'http://schema-registry.sdp-kafka.squadex.devopskzn.ru'
      swagger_kafka[0]_consumerConfig_"[security.protocol]": 'value1'
      swagger_kafka[0]_producerConfig_"[security.protocol]": 'value11'
